name: speedtest
base: core24
version: '1.2.0'
license: Proprietary
summary: Unofficial Ookla speedtest cli app
description: |
  A wrapper around the official speedtest cli tool by Ookla.
  
  **speedtest** is an application that measures the latency, jitter, packet loss, download bandwidth, 
  and upload bandwidth of the network connection between the client and a nearby Speedtest Server.

platforms:
  amd64:
  arm64:
  armhf:

grade: stable
confinement: strict

apps:
  speedtest:
    command: speedtest
    plugs:
      - network
      - network-bind

parts:
  speedtest:
    plugin: dump
    source: 
      - on amd64: https://install.speedtest.net/app/cli/ookla-speedtest-${SNAPCRAFT_PROJECT_VERSION}-linux-x86_64.tgz
      - on arm64: https://install.speedtest.net/app/cli/ookla-speedtest-${SNAPCRAFT_PROJECT_VERSION}-linux-aarch64.tgz
      - on armhf: https://install.speedtest.net/app/cli/ookla-speedtest-${SNAPCRAFT_PROJECT_VERSION}-linux-armhf.tgz
    source-type: tar
