name: Check if a new version has been released by upstream

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-snapcraft-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: install latest binary from official PPA
        id: upstream
        run: |
          sudo apt-get install curl
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt-get install speedtest
          upstream_version=$(speedtest --version | head -n 1 | awk '{print $4}' | cut -c -5)
          echo "version=$upstream_version" >> $GITHUB_OUTPUT

      - name: show upstream version
        run: |
          upstream_version=${{ steps.upstream.outputs.version }}
          if [ -z $upstream_version ]; then
            exit 1
          else
            echo "Upstream version is $upstream_version"
          fi
      
      - name: Checkout this repo on master(amd64)
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: get snap current amd64 version
        id: current_amd64
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'snap/snapcraft.yaml'

      - name: show snap current amd64 version
        run: echo "Current version is ${{ steps.current_amd64.outputs.result }}"

      - name: update to upstream's version number
        id: update_amd64
        if: steps.upstream.outputs.version != steps.current_amd64.outputs.result
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.upstream.outputs.version }}"' 'snap/snapcraft.yaml'
          
      - name: Commit changes on amd64
        if: steps.update_amd64.outcome == 'success'
        run: |
          set -x
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update snapcraft.yaml to version ${{ steps.upstream.outputs.version }}"
          git push

      - name: Checkout this repo on arm64
        uses: actions/checkout@v4
        with:
          ref: arm64
      
      - name: get snap current arm64 version
        id: current_arm64
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'snap/snapcraft.yaml'

      - name: show snap current arm64 version
        run: echo "Current version is ${{ steps.current_arm64.outputs.result }}"

      - name: update to upstream's version number
        id: update_arm64
        if: steps.upstream.outputs.version != steps.current_arm64.outputs.result
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.upstream.outputs.version }}"' 'snap/snapcraft.yaml'
          
      - name: Commit changes on arm64
        if: steps.update_arm64.outcome == 'success'
        run: |
          set -x
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update snapcraft.yaml to version ${{ steps.upstream.outputs.version }}"
          git push

      - name: Checkout this repo on armhf
        uses: actions/checkout@v4
        with:
          ref: armhf
      
      - name: get snap current armhf version
        id: current_armhf
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'snap/snapcraft.yaml'

      - name: show snap current armhf version
        run: echo "Current version is ${{ steps.current_armhf.outputs.result }}"

      - name: update to upstream's version number
        id: update_armhf
        if: steps.upstream.outputs.version != steps.current_armhf.outputs.result
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.upstream.outputs.version }}"' 'snap/snapcraft.yaml'
          
      - name: Commit changes on armhf
        if: steps.update_armhf.outcome == 'success'
        run: |
          set -x
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update snapcraft.yaml to version ${{ steps.upstream.outputs.version }}"
          git push
